name: Build

on:
  pull_request:
  push:
    branches:
      - development
    tags:
      - '*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    needs: [test]
    if: github.ref == 'refs/heads/development'
    steps:
      - uses: actions/checkout@v4
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date --utc +%Y%m%d.%H%M)"
      - name: Get sha with 8 chars long
        id: commit_sha
        run: echo "::set-output name=commit_sha::${GITHUB_SHA:0:8}"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # dependencies needed for building are amd64 only
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/scottaubrey/loris:latest
            ghcr.io/scottaubrey/loris:master-${{ steps.commit_sha.outputs.commit_sha }}-${{ steps.date.outputs.date }}
